/** RNS BigBull Player Desk: additive user controls; retains the existing dark terminal visual language. */
import { useEffect, useMemo, useState } from 'react';
import { Link } from 'wouter';
import { Bookmark, CheckCircle2, CircleHelp, Heart, KeyRound, Search, Send, ShieldCheck, Sparkles, Volume2 } from 'lucide-react';

type Tool = { id: string; name: string; detail: string; href: string };
const TOOLS: Tool[] = [
  { id: 'bio', name: 'Bio Tool', detail: 'Create and customise a player bio.', href: '/bio' },
  { id: 'vip', name: 'VIP Hub', detail: 'Open the member tools workspace.', href: '/vip' },
  { id: 'sensitivity', name: 'FF Sensitivity', detail: 'Use the existing device-based sensitivity finder.', href: '/sensitivity' },
  { id: 'headshot', name: 'Headshot %', detail: 'Check the existing practice calculator.', href: '/headshot' },
  { id: 'uid', name: 'UID Lookup', detail: 'Open the existing player lookup page.', href: '/uid' },
  { id: 'news', name: 'FF News', detail: 'Read owner-curated game news.', href: '/news' },
];
const readJson = <T,>(key: string, fallback: T): T => { try { return JSON.parse(localStorage.getItem(key) ?? '') as T; } catch { return fallback; } };

export function PlayerDeskPage() {
  const [query, setQuery] = useState('');
  const [favorites, setFavorites] = useState<string[]>(() => readJson('rns_favorite_tools', []));
  const [recent, setRecent] = useState<string[]>(() => readJson('rns_recent_tools', []));
  const [key, setKey] = useState(''); const [keyResult, setKeyResult] = useState('');
  const [request, setRequest] = useState(''); const [requestResult, setRequestResult] = useState('');
  const [onboarding, setOnboarding] = useState(() => localStorage.getItem('rns_player_intro_seen') !== 'yes');
  const [largeText, setLargeText] = useState(() => localStorage.getItem('rns_large_text') === 'yes');
  const [reducedMotion, setReducedMotion] = useState(() => localStorage.getItem('rns_reduced_motion') === 'yes');
  useEffect(() => { document.documentElement.classList.toggle('rns-large-text', largeText); localStorage.setItem('rns_large_text', largeText ? 'yes' : 'no'); }, [largeText]);
  useEffect(() => { document.documentElement.classList.toggle('rns-reduced-motion', reducedMotion); localStorage.setItem('rns_reduced_motion', reducedMotion ? 'yes' : 'no'); }, [reducedMotion]);
  const visible = useMemo(() => TOOLS.filter(t => `${t.name} ${t.detail}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const save = (next: string[], type: 'rns_favorite_tools' | 'rns_recent_tools', setter: (v: string[]) => void) => { localStorage.setItem(type, JSON.stringify(next)); setter(next); };
  const openTool = (id: string) => save([id, ...recent.filter(x => x !== id)].slice(0, 5), 'rns_recent_tools', setRecent);
  const toggleFavorite = (id: string) => save(favorites.includes(id) ? favorites.filter(x => x !== id) : [...favorites, id], 'rns_favorite_tools', setFavorites);
  async function checkKey() { const value = key.trim().toUpperCase(); if (!value) return setKeyResult('Enter your RNS key first.'); try { const res = await fetch(`/api/vip-status?key=${encodeURIComponent(value)}`); const data = await res.json(); setKeyResult(data.ok ? (data.status === 'vip' ? 'VIP access is active.' : data.status === 'blocked' ? `Access blocked: ${data.reason ?? 'contact support.'}` : 'Key is registered. Complete the existing VIP payment flow to activate access.') : (data.error ?? 'Key not found.')); } catch { setKeyResult('Could not check now. Please retry.'); } }
  async function submitRequest() { if (!request.trim()) return setRequestResult('Write your issue or feature request first.'); try { const res = await fetch('/api/tool-request', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: 'Player support request', detail: request.trim(), contact: '' }) }); const data = await res.json(); setRequestResult(data.ok ? 'Saved for the owner to review.' : (data.error ?? 'Could not save your request.')); if (data.ok) setRequest(''); } catch { setRequestResult('Network error. Please retry.'); } }
  const hasSavedKey = Boolean(localStorage.getItem('rns_vip_key'));
  return <div className="route-in mx-auto max-w-6xl space-y-6">
    <header className="flex flex-col justify-between gap-4 border-b border-border pb-5 sm:flex-row sm:items-end"><div><div className="text-mono text-[10px] uppercase tracking-[.24em] text-accent">Player workspace</div><h1 className="mt-2 text-display text-3xl font-bold">My Player Desk</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Your personal shortcuts, access help, browser-local preferences, and direct support tools.</p></div><Link href="/gateway" className="border border-primary/40 bg-primary/10 px-4 py-2 text-mono text-[10px] uppercase tracking-[.16em] text-primary">Back to gateway</Link></header>
    {onboarding ? <section className="border border-accent/35 bg-accent/10 p-4"><div className="flex items-start justify-between gap-4"><div><div className="text-mono text-[10px] uppercase tracking-[.18em] text-accent">Quick start</div><p className="mt-1 text-sm">Search a tool, save your favourites, use access help only with your own key, and contact support if a real issue remains.</p></div><button onClick={() => { localStorage.setItem('rns_player_intro_seen', 'yes'); setOnboarding(false); }} className="border border-accent/50 px-3 py-1.5 text-mono text-[9px] uppercase text-accent">Got it</button></div></section> : null}
    <section className="grid gap-4 lg:grid-cols-[1.35fr_.65fr]"><article className="border border-border bg-card/60 p-5"><div className="flex items-center gap-2"><Search size={16} className="text-accent"/><h2 className="font-semibold">Find a tool</h2></div><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search Bio, VIP, sensitivity…" className="mt-4 w-full border border-border bg-background px-3 py-2 text-sm outline-none focus:border-accent"/><div className="mt-3 grid gap-2 sm:grid-cols-2">{visible.map(t => <div key={t.id} className="border border-border bg-background/60 p-3"><div className="flex justify-between gap-2"><div><div className="text-sm font-semibold">{t.name}</div><p className="mt-1 text-xs leading-5 text-muted-foreground">{t.detail}</p></div><button onClick={() => toggleFavorite(t.id)} aria-label={`Favourite ${t.name}`} className={favorites.includes(t.id) ? 'text-rose-400' : 'text-muted-foreground'}><Heart size={16} fill={favorites.includes(t.id) ? 'currentColor' : 'none'}/></button></div><Link onClick={() => openTool(t.id)} href={t.href} className="mt-3 inline-flex text-mono text-[9px] uppercase tracking-[.15em] text-accent">Open tool →</Link></div>)}</div></article>
    <article className="border border-border bg-card/60 p-5"><div className="flex items-center gap-2"><Bookmark size={16} className="text-accent"/><h2 className="font-semibold">Your shortcuts</h2></div><p className="mt-2 text-xs text-muted-foreground">Saved only in this browser.</p><div className="mt-4 space-y-2">{favorites.length ? favorites.map(id => { const t = TOOLS.find(x => x.id === id); return t ? <Link key={id} href={t.href} onClick={() => openTool(id)} className="block border border-border px-3 py-2 text-sm hover:border-accent">★ {t.name}</Link> : null; }) : <p className="text-xs text-muted-foreground">Tap a heart to save a favourite.</p>}</div><div className="mt-5 border-t border-border pt-4 text-xs text-muted-foreground">Recently opened: {recent.length ? recent.map(id => TOOLS.find(t => t.id === id)?.name).filter(Boolean).join(' · ') : 'none yet'}</div></article></section>
    <section className="grid gap-4 md:grid-cols-2"><article className="border border-border bg-card/60 p-5"><div className="flex items-center gap-2"><KeyRound size={16} className="text-accent"/><h2 className="font-semibold">VIP access checker</h2></div><p className="mt-2 text-xs leading-5 text-muted-foreground">Check your own registered key. This does not display or store the key.</p><div className="mt-4 flex gap-2"><input value={key} onChange={e => setKey(e.target.value.toUpperCase())} placeholder="RNS-…" className="min-w-0 flex-1 border border-border bg-background px-3 py-2 text-sm"/><button onClick={checkKey} className="border border-accent/50 px-3 text-mono text-[9px] uppercase text-accent">Check</button></div>{keyResult ? <p className="mt-3 text-xs text-muted-foreground">{keyResult}</p> : null}<p className="mt-3 text-xs text-muted-foreground">{hasSavedKey ? 'A VIP key is saved in this browser.' : 'No VIP key is saved in this browser.'} <Link href="/member" className="text-accent">Recovery and activation help →</Link></p></article>
    <article className="border border-border bg-card/60 p-5"><div className="flex items-center gap-2"><CircleHelp size={16} className="text-accent"/><h2 className="font-semibold">Support and feedback</h2></div><textarea value={request} onChange={e => setRequest(e.target.value)} placeholder="Describe an issue or suggest a feature…" className="mt-4 h-20 w-full resize-none border border-border bg-background p-3 text-sm"/><div className="mt-3 flex items-center justify-between gap-3"><Link href="/support" className="text-xs text-accent">Open support guide →</Link><button onClick={submitRequest} className="inline-flex items-center gap-2 border border-accent/50 px-3 py-2 text-mono text-[9px] uppercase text-accent"><Send size={12}/> Send</button></div>{requestResult ? <p className="mt-3 text-xs text-muted-foreground">{requestResult}</p> : null}</article></section>
    <section className="grid gap-4 md:grid-cols-3"><article className="border border-border bg-card/60 p-4"><div className="flex items-center gap-2"><Volume2 size={15} className="text-accent"/><h2 className="text-sm font-semibold">Display comfort</h2></div><label className="mt-3 flex items-center justify-between text-xs">Larger text <input type="checkbox" checked={largeText} onChange={e => setLargeText(e.target.checked)}/></label><label className="mt-3 flex items-center justify-between text-xs">Reduce motion <input type="checkbox" checked={reducedMotion} onChange={e => setReducedMotion(e.target.checked)}/></label></article><Link href="/policies" className="border border-border bg-card/60 p-4 transition hover:border-accent"><ShieldCheck size={15} className="text-accent"/><h2 className="mt-3 text-sm font-semibold">Privacy and safe use</h2><p className="mt-2 text-xs text-muted-foreground">Read what the current site stores and how tools should be used.</p></Link><Link href="/gateway" className="border border-border bg-card/60 p-4 transition hover:border-accent"><CheckCircle2 size={15} className="text-accent"/><h2 className="mt-3 text-sm font-semibold">Live availability</h2><p className="mt-2 text-xs text-muted-foreground">View real tool checks, notices, and maintenance locks.</p></Link></section>
  </div>;
}
